"""add oid column to register_definitions

Revision ID: 884c7934de25
Revises: b2a1062d8287
Create Date: 2026-03-25 08:56:11.057987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '884c7934de25'
down_revision: Union[str, None] = 'b2a1062d8287'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('register_definitions', sa.Column('oid', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('register_definitions', 'oid')
    # ### end Alembic commands ###
