"""add anomaly_schedules table

Revision ID: d3e65808cf1d
Revises: 4e3e82ebbef8
Create Date: 2026-03-18 15:06:08.481301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd3e65808cf1d'
down_revision: Union[str, None] = '4e3e82ebbef8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomaly_schedules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('register_name', sa.String(length=100), nullable=False),
    sa.Column('anomaly_type', sa.String(length=20), nullable=False),
    sa.Column('anomaly_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('trigger_after_seconds', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'register_name', 'trigger_after_seconds', name='uq_anomaly_schedule_device_register_trigger')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anomaly_schedules')
    # ### end Alembic commands ###
