"""add mqtt broker settings and publish configs

Revision ID: eda1e6420ebd
Revises: d3e65808cf1d
Create Date: 2026-03-23 09:00:37.435206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eda1e6420ebd'
down_revision: Union[str, None] = 'd3e65808cf1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mqtt_broker_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('use_tls', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mqtt_publish_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('topic_template', sa.String(length=500), nullable=False),
    sa.Column('payload_mode', sa.String(length=20), nullable=False),
    sa.Column('publish_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('qos', sa.Integer(), nullable=False),
    sa.Column('retain', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mqtt_publish_configs')
    op.drop_table('mqtt_broker_settings')
    # ### end Alembic commands ###
